---
- name: Configure the mongodb instance
  hosts: all
  user: vagrant
  sudo: True
  gather_facts: False

  tasks:
    - name: Add Yum repository
      copy: src=../files/10gen.repo dest=/etc/yum.repos.d/10gen.repo
      tags: yum

#    - name: Update Yum
#      action: command yum -y update
#      tags: yumupdate

    - name: Install MongoDB packages
      yum: pkg=$item state=latest
      with_items:
        - mongo-10gen
        - mongo-10gen-server
      tags: mongodb

    - name: MongoDB | Push default configuration template
      template:
        src=../files/mongodb.conf.j2
        dest=/etc/mongodb.conf
        owner=root group=root mode=0644


- name: Start Mongo
  hosts: all
  user: vagrant
  sudo: True
  gather_facts: False

  tasks:
    - name: Create Database folder
      command: mkdir -p /home/vagrant/data
      tags: mongodb

    - name: Configure MongoDB
      service: name=mongod state=started enabled=yes
      tags: mongodb
      notify:
      - mongodb-restart

  handlers:
    - name: mongodb-restart
      service: name=mongod state=restarted
...
