---
- name: Python 2.7.5 Installation
  hosts: all
  user: vagrant
  sudo: True

  vars:
    python_path: /usr/local/bin

  tasks:
    - name: Install GCC
      action: yum name=gcc
      tags: python27

    - name: Get Python 2.7.5
      action: command wget http://www.python.org/ftp/python/2.7.5/Python-2.7.5.tgz
      tags: python27

    - name: Extract Python 2.7.5
      action: command tar xvfz Python-2.7.5.tgz
      tags: python27

    - name: Change owner (for some reason it's set at user 1000. Weird)
      action: command chown -R vagrant:vagrant Python-2.7.5
      tags: python27

    - name: Configure Python 2.7.5
      action: command ./configure chdir=/home/vagrant/Python-2.7.5
      tags: python27

    - name: Prepare Python 2.7.5 Install
      action: command make chdir=/home/vagrant/Python-2.7.5
      tags: python27

    - name: Install Python 2.7.5
      action: command make altinstall chdir=/home/vagrant/Python-2.7.5
      tags: python27

    - name: Link python 2.7 to python
      action: command ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
      tags: python27

    - name: Remove downloadfile
      action: command rm -rf /home/vagrant/Python-2.7.5*
      tags: python27

    - name: add {{python_path}} to path
      lineinfile: dest=/home/vagrant/.bash_profile
                  state=present
                  backrefs=yes
                  regexp='PATH=(["]*)((?!.*?{{python_path}}).*?)(["]*)$'
                  line="PATH={{python_path}}:\1\2\3"
      tags: python27
...