---
- name: Ruby Installation 1/3
  hosts: all
  user: vagrant
  sudo: True
  gather_facts: False

  vars:
    - rbenv_root: /home/vagrant/.rbenv/bin
    - ruby_version: 1.9.3-p385

  tasks:

    - name: Add EPEL as yum repository
      action: copy src=../files/epel.repo dest=/etc/yum.repos.d/epel.repo
      tags: epel

    - name: Create the GPG key for EPEL
      copy: src=../files/RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
      tags: epel


    - name: Install system dependencies for Ruby
      action: yum pkg={{item}} state=latest
      with_items:
        - gcc-c++
        - patch
        - readline
        - readline-devel
        - zlib
        - zlib-devel
        - libyaml-devel
        - libffi-devel
        - openssl-devel
        - make
        - bzip2
        - autoconf
        - automake
        - libtool
        - bison
        #- iconv-devel
        - git-core
        - curl-devel
      tags: ruby


- name: Ruby Installation 2/3
  hosts: all
  user: vagrant
  sudo: False

  tasks:

    - name: Getting Ruby Rbenv from GitHub
      git: repo=git://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
      tags: ruby

    - name: Getting Ruby Plugins from Github
      git: repo=git://github.com/sstephenson/ruby-build.git dest=/home/vagrant/.rbenv/plugins/ruby-build
      tags: ruby

    - name: add Ruby environment variables to path
      lineinfile: dest=/home/vagrant/.bash_profile regexp={{item}} line={{item}}
      with_items:
        - "'export\ RUBY_CFLAGS=\"-march=native\ -O3\"'"
        - export\ PATH=$HOME/.rbenv/bin:$PATH
        - "'eval \"$(rbenv init -)\"'"
      tags: ruby

    - name: Installing Ruby 1.9.3-p392 via rbenv
      command: /home/vagrant/.rbenv/bin/rbenv install -f 1.9.3-p392
      tags: ruby

    - name: Making Ruby 1.9.3-p392 default
      command: /home/vagrant/.rbenv/bin/rbenv global 1.9.3-p392
      tags: ruby

    - name: Prevent gem from installing local documentation (saves time)
      copy:
        src=../files/gemrc
        dest=/home/vagrant/.gemrc
      tags: ruby

    - name: install Bundler
      command: /home/vagrant/.rbenv/shims/gem install bundler
      tags: ruby1

    - name: rbenv | rehash
      command: /home/vagrant/.rbenv/bin/rbenv rehash
      tags: ruby2
...
