---
  #details for accessing mongodb
  database:
    host: "localhost"
    user: "root"
    passwd: ""
    db-name: ""
    port: 27017
  #prefix for tfidf, lda and esa model
  prefix: "vagrant/data/wiki"
  #minimum rating for top-news
  rating: 0.1
  #config for flask
  flask:
    secret_key: "very secret"
    debug: True

  directory: ../data/wiki_wordids.dict
...
