---
- hosts: all
  name: Configure ntpd
  user: vagrant
  sudo: True
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

- hosts: all
  name: Configure packages
  user: vagrant
  sudo: True
  tasks:
    - name: Add Yum repository
      action: copy src=../provisioning/files/10gen.repo dest=/etc/yum.repos.d/10gen.repo

    - name: Install packages
      action: yum pkg=$item state=latest
      with_items:
        - mongo-10gen
        - mongo-10gen-server

    - name: Configure MongoDB
      action: service name=mongod state=started enabled=yes

    - name: Add EPEL as yum repository
      action: copy src=../provisioning/files/epel.repo dest=/etc/yum.repos.d/epel.repo
      tags: python

    - name: Create the GPG key for EPEL
      copy: src=../provisioning/files/RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
      tags: python

    - name: Install Python pip
      action: yum pkg=python-pip state=installed
      tags: python




  #include: playbooks/mongodb.yml
...