---
- hosts: all
  name: Configure ntpd
  user: vagrant
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

- hosts: all
  name: Copy MongoDB repo file
  user: vagrant
  sudo: True
  tasks:
    - name: Add Yum repository
      action: copy src=../provisioning/files/10gen.repo dest=/etc/yum.repos.d/10gen.repo

    - name: Install packages
      action: yum pkg=$item state=latest
      with_items:
        - mongo-10gen
        - mongo-10gen-server

    - name: Configure MongoDB
      action: service name=mongod state=started enabled=yes




  #include: playbooks/mongodb.yml
...